In [3]:
# to create a dataframe manually - from a dictionary
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'Country': ['USA','Australia', 'Mexico']}
df = pd.DataFrame(data)
print(df)

      Name  Age    Country
0    Alice   25        USA
1      Bob   30  Australia
2  Charlie   35     Mexico

In [6]:
# to see the dataframe from a csv file
import pandas as pd

df = pd.read_csv("orders.csv")
print(df)

      OrderID     CustomerName        Product         Category  Quantity  \
0           1       Eric Allen         Jacket         Clothing         5
1           2    Dana Williams        Stapler       Stationery         1
2           3  Melinda Shelton        T-Shirt         Clothing         5
3           4   Jessica Horton  Standing Desk        Furniture        10
4           5  Melissa Simmons          Bread  Food & Beverage        15
...       ...              ...            ...              ...       ...
4995     4996        Debra Lee         Jacket         Clothing         8
4996     4997   Ashlee Montoya         Laptop      Electronics        14
4997     4998  Stephen Kennedy       Notebook       Stationery         9
4998     4999  Jeremiah Krause        T-Shirt         Clothing         1
4999     5000      Maxwell Kim         Jacket         Clothing         1

        Price   OrderDate Shipped      Country
0      582.80  2026-10-07     Yes       Sweden
1      202.96  2025-01-28     Yes           UK
2     1093.40  2024-08-18      No        India
3      363.78  2025-01-31      No  South Korea
4     1388.60  2025-08-03      No       Brazil
...       ...         ...     ...          ...
4995   864.64  2024-02-13     Yes  Netherlands
4996  1555.36  2024-07-11     Yes  South Korea
4997  2045.90  2026-01-11     Yes       Sweden
4998  2225.73  2024-06-07     Yes        Japan
4999   810.71  2026-05-31     Yes    Singapore

[5000 rows x 9 columns]

In [4]:
# to see the dataframe from a excel file
import pandas as pd

df = pd.read_excel("orders.xlsx")
print(df)

      OrderID     CustomerName        Product         Category  Quantity  \
0           1       Eric Allen         Jacket         Clothing         5
1           2    Dana Williams        Stapler       Stationery         1
2           3  Melinda Shelton        T-Shirt         Clothing         5
3           4   Jessica Horton  Standing Desk        Furniture        10
4           5  Melissa Simmons          Bread  Food & Beverage        15
...       ...              ...            ...              ...       ...
4995     4996        Debra Lee         Jacket         Clothing         8
4996     4997   Ashlee Montoya         Laptop      Electronics        14
4997     4998  Stephen Kennedy       Notebook       Stationery         9
4998     4999  Jeremiah Krause        T-Shirt         Clothing         1
4999     5000      Maxwell Kim         Jacket         Clothing         1

        Price  OrderDate Shipped      Country
0      582.80 2026-10-07     Yes       Sweden
1      202.96 2025-01-28     Yes           UK
2     1093.40 2024-08-18      No        India
3      363.78 2025-01-31      No  South Korea
4     1388.60 2025-08-03      No       Brazil
...       ...        ...     ...          ...
4995   864.64 2024-02-13     Yes  Netherlands
4996  1555.36 2024-07-11     Yes  South Korea
4997  2045.90 2026-01-11     Yes       Sweden
4998  2225.73 2024-06-07     Yes        Japan
4999   810.71 2026-05-31     Yes    Singapore

[5000 rows x 9 columns]

In [12]:
df.head()     # shows the first 5 rows

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1,Eric Allen,Jacket,Clothing,5,582.80,2026-10-07,Yes,Sweden
1,2,Dana Williams,Stapler,Stationery,1,202.96,2025-01-28,Yes,UK
2,3,Melinda Shelton,T-Shirt,Clothing,5,1093.40,2024-08-18,No,India
3,4,Jessica Horton,Standing Desk,Furniture,10,363.78,2025-01-31,No,South Korea
4,5,Melissa Simmons,Bread,Food & Beverage,15,1388.60,2025-08-03,No,Brazil

In [15]:
df.tail()     # shows the last 5 rows

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
4995,4996,Debra Lee,Jacket,Clothing,8,864.64,2024-02-13,Yes,Netherlands
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea
4997,4998,Stephen Kennedy,Notebook,Stationery,9,2045.90,2026-01-11,Yes,Sweden
4998,4999,Jeremiah Krause,T-Shirt,Clothing,1,2225.73,2024-06-07,Yes,Japan
4999,5000,Maxwell Kim,Jacket,Clothing,1,810.71,2026-05-31,Yes,Singapore

In [16]:
df.info()     # gives the general info. of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       5000 non-null   int64
 1   CustomerName  5000 non-null   object
 2   Product       5000 non-null   object
 3   Category      5000 non-null   object
 4   Quantity      5000 non-null   int64
 5   Price         5000 non-null   float64
 6   OrderDate     5000 non-null   datetime64[ns]
 7   Shipped       5000 non-null   object
 8   Country       5000 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 351.7+ KB

In [19]:
df.describe()       # summaries the dataframe

           OrderID     Quantity        Price                   OrderDate
count  5000.000000  5000.000000  5000.000000                        5000
mean   2500.500000     7.996400  1258.417584  2025-07-09 02:30:54.720000
min       1.000000     1.000000     5.530000         2024-01-01 00:00:00
25%    1250.750000     4.000000   640.145000         2024-10-12 00:00:00
50%    2500.500000     8.000000  1253.555000         2025-07-06 00:00:00
75%    3750.250000    12.000000  1881.872500         2026-04-10 00:00:00
max    5000.000000    15.000000  2500.000000         2026-12-31 00:00:00
std    1443.520003     4.310557   719.513360                         NaN

In [20]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [21]:
df.index      # gives the range of the dataframe

RangeIndex(start=0, stop=5000, step=1)

In [25]:
df["Product"]

0              Jacket
1             Stapler
2             T-Shirt
3       Standing Desk
4               Bread
            ...
4995           Jacket
4996           Laptop
4997         Notebook
4998          T-Shirt
4999           Jacket
Name: Product, Length: 5000, dtype: object

In [26]:
len(df["Product"])

5000

In [27]:
df[["Product", "Country"]]

            Product      Country
0            Jacket       Sweden
1           Stapler           UK
2           T-Shirt        India
3     Standing Desk  South Korea
4             Bread       Brazil
...             ...          ...
4995         Jacket  Netherlands
4996         Laptop  South Korea
4997       Notebook       Sweden
4998        T-Shirt        Japan
4999         Jacket    Singapore

[5000 rows x 2 columns]

In [30]:
df.iloc[0]          # gives all the values of the 0th indexed row {i.e. 1st row}

OrderID                           1
CustomerName             Eric Allen
Product                      Jacket
Category                   Clothing
Quantity                          5
Price                         582.8
OrderDate       2026-10-07 00:00:00
Shipped                         Yes
Country                      Sweden
Name: 0, dtype: object

In [32]:
df.iloc[0]["Country"]          # fetches the value of the 10th indexed row {i.e. 11th row}'s column mentioned - here Country of 11th row

'Sweden'

In [33]:
df[df["Category"] == "Electronics"]                  # fetching data from condition

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
5,6,Lisa Houston,Webcam,Electronics,7,1938.06,2025-04-26,Yes,Japan
9,10,James Pollard,Keyboard,Electronics,11,2349.55,2026-10-02,Yes,USA
18,19,Henry Stevens,Monitor,Electronics,9,896.42,2025-06-06,Yes,Spain
19,20,Molly Giles,Laptop,Electronics,2,1099.55,2024-09-15,Yes,Mexico
21,22,Russell Walker,Mouse,Electronics,10,1617.51,2026-12-26,Yes,Italy
...,...,...,...,...,...,...,...,...,...
4975,4976,Andrea Wallace,Webcam,Electronics,3,1141.00,2025-11-17,No,Spain
4979,4980,Joe Gill,USB Drive,Electronics,4,1248.60,2024-11-30,Yes,USA
4980,4981,Melissa Greene,Laptop,Electronics,8,1249.15,2024-07-23,Yes,Canada
4985,4986,Mr. Stephen Hernandez,Laptop,Electronics,9,328.24,2025-07-27,Yes,South Africa
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea

In [41]:
df[(df["Category"] == "Electronics") & (df["Country"] == "USA")]                  # fetching data  using logic operator (and)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,10,James Pollard,Keyboard,Electronics,11,2349.55,2026-10-02,Yes,USA
50,51,Ariel Alexander,Laptop,Electronics,8,523.17,2025-09-05,Yes,USA
80,81,Brandy Gay,Smartphone,Electronics,15,1420.28,2024-08-09,Yes,USA
84,85,Ryan Joseph,Tablet,Electronics,2,2167.27,2026-05-08,No,USA
479,480,Joshua Kim,Headphones,Electronics,8,2151.27,2026-03-15,No,USA
949,950,Tracy Thornton,Tablet,Electronics,11,920.36,2026-12-06,Yes,USA
1016,1017,Hunter Curtis,Headphones,Electronics,8,1381.98,2025-06-08,No,USA
1245,1246,Sean Villanueva,Monitor,Electronics,1,405.77,2025-02-27,Yes,USA
1616,1617,Brian Jackson,Webcam,Electronics,9,1152.48,2026-04-01,Yes,USA
1661,1662,Douglas Berry,Webcam,Electronics,15,2496.74,2024-02-16,Yes,USA
1702,1703,Hannah Brown,Webcam,Electronics,15,1140.57,2026-11-14,No,USA
1743,1744,Andrew Salazar,Mouse,Electronics,10,1681.26,2025-02-27,No,USA
1827,1828,Toni Kaufman,Keyboard,Electronics,4,2271.95,2025-01-30,No,USA
1930,1931,Taylor Barton,Webcam,Electronics,7,981.58,2024-06-29,Yes,USA
2205,2206,Paul Walker,USB Drive,Electronics,5,670.55,2026-08-01,No,USA
2215,2216,Cole Williams,Monitor,Electronics,8,2321.57,2026-03-16,Yes,USA
2222,2223,Laura Joseph,Headphones,Electronics,3,755.80,2024-09-27,No,USA
2418,2419,Jeremy Hunter,Tablet,Electronics,6,1834.15,2024-07-04,No,USA
2442,2443,Kevin Evans,Monitor,Electronics,10,2340.80,2025-02-11,Yes,USA
2456,2457,Mary Adams,Headphones,Electronics,8,1528.63,2025-09-22,Yes,USA
2552,2553,Christopher Mendoza,Smartphone,Electronics,6,2172.47,2024-10-28,Yes,USA
2635,2636,Katherine Harmon,Webcam,Electronics,8,760.19,2026-03-04,Yes,USA
2869,2870,Jacqueline Blackwell,Webcam,Electronics,8,1832.80,2025-04-04,Yes,USA
3008,3009,William Lin,Tablet,Electronics,13,2179.98,2024-06-03,Yes,USA
3150,3151,Ryan Hoover,Headphones,Electronics,6,166.32,2024-10-14,Yes,USA
3321,3322,Kelly Reid,Smartphone,Electronics,4,1933.00,2025-12-08,Yes,USA
3371,3372,Phillip Harrison,Headphones,Electronics,14,2088.00,2026-04-28,Yes,USA
3460,3461,Barbara Estrada,USB Drive,Electronics,15,1297.60,2025-06-20,Yes,USA
3474,3475,Eric Burns,Webcam,Electronics,4,1631.26,2025-05-30,No,USA
3589,3590,David Hoover,Tablet,Electronics,3,834.13,2024-05-13,Yes,USA
3625,3626,Dr. Victoria Harris,Printer,Electronics,2,758.90,2026-03-19,No,USA
3848,3849,Ashlee Brown,Mouse,Electronics,13,169.40,2025-12-18,No,USA
3867,3868,Adriana Barrett,Laptop,Electronics,12,768.04,2026-11-14,Yes,USA
3943,3944,Melissa Mullen,Monitor,Electronics,8,2190.11,2024-07-21,Yes,USA
4221,4222,Richard Sanchez,Webcam,Electronics,11,2478.87,2024-09-25,Yes,USA
4266,4267,Sarah Frazier,Mouse,Electronics,10,1576.05,2025-05-10,Yes,USA
4410,4411,Amanda Mcguire,Webcam,Electronics,12,1641.64,2026-12-11,Yes,USA
4691,4692,Alexis Lam,Laptop,Electronics,3,417.62,2025-01-28,Yes,USA
4714,4715,Timothy Lopez,Keyboard,Electronics,5,605.37,2024-05-23,Yes,USA
4822,4823,Aaron Jenkins,Headphones,Electronics,11,863.48,2026-09-05,No,USA
4886,4887,Mitchell Chen,Smartphone,Electronics,2,1442.88,2026-03-08,Yes,USA
4944,4945,Michael Walton,Headphones,Electronics,8,2116.90,2024-09-09,Yes,USA
4979,4980,Joe Gill,USB Drive,Electronics,4,1248.60,2024-11-30,Yes,USA

In [42]:
df[(df["Category"] == "Electronics") | (df["Country"] == "USA")]                   # fetching data  using logic operator (or)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
5,6,Lisa Houston,Webcam,Electronics,7,1938.06,2025-04-26,Yes,Japan
9,10,James Pollard,Keyboard,Electronics,11,2349.55,2026-10-02,Yes,USA
18,19,Henry Stevens,Monitor,Electronics,9,896.42,2025-06-06,Yes,Spain
19,20,Molly Giles,Laptop,Electronics,2,1099.55,2024-09-15,Yes,Mexico
21,22,Russell Walker,Mouse,Electronics,10,1617.51,2026-12-26,Yes,Italy
...,...,...,...,...,...,...,...,...,...
4979,4980,Joe Gill,USB Drive,Electronics,4,1248.60,2024-11-30,Yes,USA
4980,4981,Melissa Greene,Laptop,Electronics,8,1249.15,2024-07-23,Yes,Canada
4985,4986,Mr. Stephen Hernandez,Laptop,Electronics,9,328.24,2025-07-27,Yes,South Africa
4991,4992,Lindsey Hart,File Cabinet,Furniture,10,2426.67,2025-02-12,Yes,USA
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea

In [44]:
df[df["Quantity"] > 10]                  # fetching data using comparison operator

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
4,5,Melissa Simmons,Bread,Food & Beverage,15,1388.60,2025-08-03,No,Brazil
7,8,Dave Velasquez,Scarf,Clothing,13,272.35,2025-10-19,No,UK
9,10,James Pollard,Keyboard,Electronics,11,2349.55,2026-10-02,Yes,USA
11,12,Matthew Anderson,Desk Lamp,Furniture,14,1388.02,2024-05-26,Yes,South Africa
13,14,Marie Poole,Bed,Furniture,14,1622.18,2024-11-10,Yes,Spain
...,...,...,...,...,...,...,...,...,...
4977,4978,Andrea Dalton,Snack Bar,Food & Beverage,12,1099.52,2024-04-12,No,UAE
4983,4984,Robert Terry,Pen,Stationery,12,211.83,2025-01-04,Yes,Canada
4984,4985,Janet Bush,Pen,Stationery,13,106.24,2025-04-14,Yes,India
4986,4987,Sophia Warner,Pen,Stationery,14,121.93,2025-04-16,No,Germany
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea

In [46]:
df[df["CustomerName"].str.startswith('A')]               # filters with starting letter in a specific feature [column]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
23,24,Andrea Arroyo,Ruler,Stationery,5,1671.76,2024-02-12,No,USA
25,26,Arthur Edwards,Bottled Water,Food & Beverage,8,84.05,2024-04-08,No,Germany
41,42,Ashley Myers,Tablet,Electronics,4,793.26,2024-07-16,Yes,UAE
47,48,Aaron Hill Jr.,Dining Table,Furniture,3,1295.56,2024-06-10,Yes,Australia
50,51,Ariel Alexander,Laptop,Electronics,8,523.17,2025-09-05,Yes,USA
...,...,...,...,...,...,...,...,...,...
4973,4974,Alan Stevens,Socks,Clothing,13,706.35,2025-10-12,No,South Africa
4975,4976,Andrea Wallace,Webcam,Electronics,3,1141.00,2025-11-17,No,Spain
4977,4978,Andrea Dalton,Snack Bar,Food & Beverage,12,1099.52,2024-04-12,No,UAE
4988,4989,Andrew Willis,Pen,Stationery,8,1675.57,2025-09-28,Yes,Canada
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea

In [49]:
df[df["CustomerName"].str.endswith('a')]               # filters with ending letter in a specific feature [column]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
17,18,Manuel Ibarra,Notebook,Stationery,11,672.27,2025-10-11,Yes,Australia
31,32,Douglas Ortega,Laptop,Electronics,3,618.72,2026-05-23,Yes,Australia
42,43,Louis Garcia,Snack Bar,Food & Beverage,15,559.84,2026-02-20,Yes,UAE
73,74,Richard Garcia,Office Chair,Furniture,4,965.79,2025-02-13,Yes,Italy
76,77,Shannon Figueroa,Hat,Clothing,14,2009.39,2024-02-21,No,UAE
...,...,...,...,...,...,...,...,...,...
4819,4820,Andrea Rivera,Coffee Beans,Food & Beverage,2,1364.70,2026-05-25,No,Spain
4851,4852,Javier Medina,Tape,Stationery,14,295.08,2026-11-10,Yes,South Korea
4852,4853,Eric Mendoza,Monitor,Electronics,12,1918.43,2026-11-18,Yes,UAE
4906,4907,Dana Rivera,Pencil,Stationery,11,1531.47,2025-03-28,No,Japan
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea

In [6]:
df[df["Country"].isin(["UAE", "Australia", "Spain"])]               # takes full row that are in the list of countries

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
13,14,Marie Poole,Bed,Furniture,14,1622.18,2024-11-10,Yes,Spain
14,15,Sarah Fox,Hat,Clothing,6,1201.32,2026-09-14,Yes,UAE
15,16,Gregory Perez,T-Shirt,Clothing,3,432.32,2025-12-12,No,Spain
17,18,Manuel Ibarra,Notebook,Stationery,11,672.27,2025-10-11,Yes,Australia
18,19,Henry Stevens,Monitor,Electronics,9,896.42,2025-06-06,Yes,Spain
...,...,...,...,...,...,...,...,...,...
4970,4971,April Watts,Sneakers,Clothing,6,1801.86,2026-06-28,Yes,Australia
4975,4976,Andrea Wallace,Webcam,Electronics,3,1141.00,2025-11-17,No,Spain
4977,4978,Andrea Dalton,Snack Bar,Food & Beverage,12,1099.52,2024-04-12,No,UAE
4981,4982,Donald Mann Jr.,Pencil,Stationery,3,2292.58,2026-04-23,Yes,Spain
4994,4995,Tina King,T-Shirt,Clothing,7,1683.20,2024-10-29,Yes,Australia

In [7]:
df[~df["Country"].isin(["UAE", "Australia", "Spain"])]               # '~' is like NOT in the list

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1,Eric Allen,Jacket,Clothing,5,582.80,2026-10-07,Yes,Sweden
1,2,Dana Williams,Stapler,Stationery,1,202.96,2025-01-28,Yes,UK
2,3,Melinda Shelton,T-Shirt,Clothing,5,1093.40,2024-08-18,No,India
3,4,Jessica Horton,Standing Desk,Furniture,10,363.78,2025-01-31,No,South Korea
4,5,Melissa Simmons,Bread,Food & Beverage,15,1388.60,2025-08-03,No,Brazil
...,...,...,...,...,...,...,...,...,...
4995,4996,Debra Lee,Jacket,Clothing,8,864.64,2024-02-13,Yes,Netherlands
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea
4997,4998,Stephen Kennedy,Notebook,Stationery,9,2045.90,2026-01-11,Yes,Sweden
4998,4999,Jeremiah Krause,T-Shirt,Clothing,1,2225.73,2024-06-07,Yes,Japan
4999,5000,Maxwell Kim,Jacket,Clothing,1,810.71,2026-05-31,Yes,Singapore

In [9]:
# now if I want to update a column with a Customer name, what can I do?

df.loc[df["CustomerName"] == "Stephen Kennedy"]                   # so first I see whether the customername is unique or any repeatation happen

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
4997,4998,Stephen Kennedy,Notebook,Stationery,9,2045.9,2026-01-11,Yes,Sweden

In [10]:
df.loc[df["CustomerName"] == "Stephen Kennedy", 'Product'] = "MacBook"

# > df.loc[df["CustomerName"] == "Stephen Kennedy", < for locating the data; >, 'Product'< is the column to update; 
# and the >] = "MacBook"< is the value to update

In [11]:
# now if i check again his product
df.loc[df["CustomerName"] == "Stephen Kennedy"]                   # it will be updated

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
4997,4998,Stephen Kennedy,MacBook,Stationery,9,2045.9,2026-01-11,Yes,Sweden

In [13]:
# another example

df.loc[df["Country"] == "USA"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,10,James Pollard,Keyboard,Electronics,11,2349.55,2026-10-02,Yes,USA
22,23,Beverly Walsh,Desk Lamp,Furniture,14,800.30,2026-01-28,Yes,USA
23,24,Andrea Arroyo,Ruler,Stationery,5,1671.76,2024-02-12,No,USA
49,50,Stephanie Lyons,Stapler,Stationery,14,2179.46,2025-04-28,Yes,USA
50,51,Ariel Alexander,Laptop,Electronics,8,523.17,2025-09-05,Yes,USA
...,...,...,...,...,...,...,...,...,...
4944,4945,Michael Walton,Headphones,Electronics,8,2116.90,2024-09-09,Yes,USA
4945,4946,Steven Johnson,Socks,Clothing,15,169.82,2026-08-15,Yes,USA
4958,4959,Jill Roberts,Bottled Water,Food & Beverage,7,1468.89,2025-01-09,Yes,USA
4979,4980,Joe Gill,USB Drive,Electronics,4,1248.60,2024-11-30,Yes,USA
4991,4992,Lindsey Hart,File Cabinet,Furniture,10,2426.67,2025-02-12,Yes,USA

In [14]:
df.loc[df["Country"] == "USA", "Country"] = "United States"              # now I change the USA --> United States

In [16]:
df.loc[df["Country"] == "United States"]                     # now if i run with United States, there won't be any USA as country

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,10,James Pollard,Keyboard,Electronics,11,2349.55,2026-10-02,Yes,United States
22,23,Beverly Walsh,Desk Lamp,Furniture,14,800.30,2026-01-28,Yes,United States
23,24,Andrea Arroyo,Ruler,Stationery,5,1671.76,2024-02-12,No,United States
49,50,Stephanie Lyons,Stapler,Stationery,14,2179.46,2025-04-28,Yes,United States
50,51,Ariel Alexander,Laptop,Electronics,8,523.17,2025-09-05,Yes,United States
...,...,...,...,...,...,...,...,...,...
4944,4945,Michael Walton,Headphones,Electronics,8,2116.90,2024-09-09,Yes,United States
4945,4946,Steven Johnson,Socks,Clothing,15,169.82,2026-08-15,Yes,United States
4958,4959,Jill Roberts,Bottled Water,Food & Beverage,7,1468.89,2025-01-09,Yes,United States
4979,4980,Joe Gill,USB Drive,Electronics,4,1248.60,2024-11-30,Yes,United States
4991,4992,Lindsey Hart,File Cabinet,Furniture,10,2426.67,2025-02-12,Yes,United States

In [17]:
# to make every country with Caps
df["Country"] = df["Country"].str.upper()

In [18]:
df["Country"]

0            SWEDEN
1                UK
2             INDIA
3       SOUTH KOREA
4            BRAZIL
           ...
4995    NETHERLANDS
4996    SOUTH KOREA
4997         SWEDEN
4998          JAPAN
4999      SINGAPORE
Name: Country, Length: 5000, dtype: object

In [19]:
# to make every country with Title case
df["Country"] = df["Country"].str.title()

In [20]:
df["Country"]

0            Sweden
1                Uk
2             India
3       South Korea
4            Brazil
           ...
4995    Netherlands
4996    South Korea
4997         Sweden
4998          Japan
4999      Singapore
Name: Country, Length: 5000, dtype: object

In [25]:
# if you want to delete a row from a dataframe
df = df.drop(4998)

In [26]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
4993,4994,Tiffany Nelson,Bottled Water,Food & Beverage,9,1662.36,2024-10-29,No,India
4994,4995,Tina King,T-Shirt,Clothing,7,1683.20,2024-10-29,Yes,Australia
4995,4996,Debra Lee,Jacket,Clothing,8,864.64,2024-02-13,Yes,Netherlands
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea
4997,4998,Stephen Kennedy,MacBook,Stationery,9,2045.90,2026-01-11,Yes,Sweden

In [31]:
# === CLEANING DATA ===
df.dropna()                  # cleaning the row with NaN values
df.fillna({"OrderID": 0}, inplace=True)        # fills the row with NaN values with OrderID = 0

In [32]:
df

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1,Eric Allen,Jacket,Clothing,5,582.80,2026-10-07,Yes,Sweden
1,2,Dana Williams,Stapler,Stationery,1,202.96,2025-01-28,Yes,Uk
2,3,Melinda Shelton,T-Shirt,Clothing,5,1093.40,2024-08-18,No,India
3,4,Jessica Horton,Standing Desk,Furniture,10,363.78,2025-01-31,No,South Korea
4,5,Melissa Simmons,Bread,Food & Beverage,15,1388.60,2025-08-03,No,Brazil
...,...,...,...,...,...,...,...,...,...
4993,4994,Tiffany Nelson,Bottled Water,Food & Beverage,9,1662.36,2024-10-29,No,India
4994,4995,Tina King,T-Shirt,Clothing,7,1683.20,2024-10-29,Yes,Australia
4995,4996,Debra Lee,Jacket,Clothing,8,864.64,2024-02-13,Yes,Netherlands
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea
4997,4998,Stephen Kennedy,MacBook,Stationery,9,2045.90,2026-01-11,Yes,Sweden

In [33]:
df.rename(columns = {"OrderID": "Order_ID"}, inplace = True)         # renames the column, OrderID --> Order_ID

In [34]:
df

,Order_ID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1,Eric Allen,Jacket,Clothing,5,582.80,2026-10-07,Yes,Sweden
1,2,Dana Williams,Stapler,Stationery,1,202.96,2025-01-28,Yes,Uk
2,3,Melinda Shelton,T-Shirt,Clothing,5,1093.40,2024-08-18,No,India
3,4,Jessica Horton,Standing Desk,Furniture,10,363.78,2025-01-31,No,South Korea
4,5,Melissa Simmons,Bread,Food & Beverage,15,1388.60,2025-08-03,No,Brazil
...,...,...,...,...,...,...,...,...,...
4993,4994,Tiffany Nelson,Bottled Water,Food & Beverage,9,1662.36,2024-10-29,No,India
4994,4995,Tina King,T-Shirt,Clothing,7,1683.20,2024-10-29,Yes,Australia
4995,4996,Debra Lee,Jacket,Clothing,8,864.64,2024-02-13,Yes,Netherlands
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea
4997,4998,Stephen Kennedy,MacBook,Stationery,9,2045.90,2026-01-11,Yes,Sweden

In [35]:
df.rename(columns = {"CustomerName": "Customer_Name", "OrderDate": "Order_Date"}, inplace = True)         # renaming many columns

In [36]:
df

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Order_Date,Shipped,Country
0,1,Eric Allen,Jacket,Clothing,5,582.80,2026-10-07,Yes,Sweden
1,2,Dana Williams,Stapler,Stationery,1,202.96,2025-01-28,Yes,Uk
2,3,Melinda Shelton,T-Shirt,Clothing,5,1093.40,2024-08-18,No,India
3,4,Jessica Horton,Standing Desk,Furniture,10,363.78,2025-01-31,No,South Korea
4,5,Melissa Simmons,Bread,Food & Beverage,15,1388.60,2025-08-03,No,Brazil
...,...,...,...,...,...,...,...,...,...
4993,4994,Tiffany Nelson,Bottled Water,Food & Beverage,9,1662.36,2024-10-29,No,India
4994,4995,Tina King,T-Shirt,Clothing,7,1683.20,2024-10-29,Yes,Australia
4995,4996,Debra Lee,Jacket,Clothing,8,864.64,2024-02-13,Yes,Netherlands
4996,4997,Ashlee Montoya,Laptop,Electronics,14,1555.36,2024-07-11,Yes,South Korea
4997,4998,Stephen Kennedy,MacBook,Stationery,9,2045.90,2026-01-11,Yes,Sweden

In [38]:
df["Country"].value_counts()        # displays the occurence of the specificed column's each data

Country
Italy            283
Uae              274
Germany          270
Spain            270
South Africa     269
Japan            264
South Korea      259
Singapore        254
India            253
France           252
Australia        250
Sweden           250
Argentina        243
United States    240
Brazil           235
China            234
Uk               232
Canada           228
Netherlands      222
Mexico           216
Name: count, dtype: int64

In [39]:
df.groupby("Country")["Price"].sum()

Country
Argentina        300452.44
Australia        306767.58
Brazil           278378.60
Canada           290965.67
China            301741.06
France           312926.55
Germany          325758.42
India            321927.90
Italy            369097.24
Japan            334406.35
Mexico           264821.64
Netherlands      296765.70
Singapore        318349.27
South Africa     345606.55
South Korea      329558.16
Spain            327329.51
Sweden           322170.89
Uae              349782.17
Uk               282164.42
United States    310081.36
Name: Price, dtype: float64

In [41]:
df.sort_values("Price", ascending = False)           # sorting in descending order of Price column

,Order_ID,Customer_Name,Product,Category,Quantity,Price,Order_Date,Shipped,Country
3026,3027,Brooke Chung,Desk Lamp,Furniture,9,2500.00,2026-11-22,Yes,Uae
2904,2905,Terry Burns,Laptop,Electronics,13,2499.69,2026-12-02,Yes,Uae
1012,1013,Andrew Lopez,Notebook,Stationery,4,2498.98,2025-04-26,No,Japan
3545,3546,Joseph Grimes,Tape,Stationery,12,2498.93,2026-02-17,Yes,Brazil
971,972,Edward Frank,Tablet,Electronics,6,2498.20,2024-03-24,Yes,Australia
...,...,...,...,...,...,...,...,...,...
91,92,Jessica Burns,Scarf,Clothing,13,6.76,2026-03-18,No,Italy
3832,3833,Jimmy Greer,Bottled Water,Food & Beverage,6,6.35,2025-12-15,No,India
1892,1893,Sherry Reed,Socks,Clothing,11,6.31,2025-10-28,Yes,Japan
4925,4926,Susan Weber,Bed,Furniture,13,5.82,2026-11-14,No,Uk
3332,3333,Aaron Frye,USB Drive,Electronics,6,5.53,2026-08-20,Yes,South Africa

In [46]:
# now if you want to save all the changes you made from first, you can save as seperate csv file
df.to_csv("modified_orders.csv", index=False)       # making 'index = True' will add a column for indexing each row; or else only the data